export const priceList = [
  {
    id: 1,
    service: 'Ноги до/выше колен (+пальчики)',
    price: 250,
    priority: 'mean',
  },
  {
    id: 2,
    service: 'Ноги полностью(+пальчики)',
    price: 400,
    priority: 'mean',
  },
  {
    id: 3,
    service: 'Руки до локтя',
    price: 150,
    priority: 'mean',
  },
  {
    id: 4,
    service: 'Руки полностью',
    price: 250,
    priority: 'mean',
  },
  {
    id: 5,
    service: 'Бикини классическое (+дорожка)',
    price: 250,
    priority: 'mean',
  },
  {
    id: 6,
    service: 'Бикини глубокое (+дорожка)',
    price: 350,
    priority: 'mean',
  },
  {
    id: 7,
    service: 'Ягодицы',
    price: 150,
    priority: 'mean',
  },
  {
    id: 8,
    service: 'Бедра',
    price: 200,
    priority: 'mean',
  },
  {
    id: 9,
    service: 'Живот',
    price: 150,
    priority: 'mean',
  },
  {
    id: 10,
    service: 'Поясница',
    price: 150,
    priority: 'mean',
  },
  {
    id: 11,
    service: 'Подмышки',
    price: 120,
    priority: 'mean',
  },
  {
    id: 12,
    service: 'Верхняя губа (усики)',
    price: 80,
    priority: 'mean',
  },
  {
    id: 13,
    service: 'Подбородок',
    price: 80,
    priority: 'mean',
  },
  {
    id: 14,
    service: 'Виски',
    price: 80,
    priority: 'mean',
  },
  {
    id: 15,
    service: 'Щеки',
    price: 80,
    priority: 'mean',
  },
  {
    id: 16,
    service: 'Нос(волосы в носу)',
    price: 80,
    priority: 'mean',
  },
  {
    id: 17,
    service: 'Вокруг бровей',
    price: 80,
    priority: 'mean',
  },
  {
    id: 18,
    service: 'Лицо полностью',
    price: 200,
    priority: 'mean',
  },
  {
    id: 19,
    service: 'Спина',
    price: 200,
    priority: 'mean',
  },
  {
    id: 20,
    service: 'Белая линия живота',
    price: 80,
    priority: 'mean',
  },
  {
    id: 21,
    service: 'Ореолы',
    price: 80,
    priority: 'mean',
  },
];

export const additionallyPriceList = [
  {
    id: 22,
    service: 'Лечение вросших волос',
    include: ['Зона бикини', 'кислотный или энзимный пилинг', 'механическая чистка', 'SOSмаска'],
    price: 350,
    priority: 'additionally',
  },
  {
    id: 23,
    service: 'Скраб/энзимы перед эпиляцией',
    price: 80,
    priority: 'additionally',
  },
  {
    id: 24,
    service: 'SOSмаска отбеливающая и Противовоспалительная',
    price: 100,
    priority: 'additionally',
  },
]
